### PR TITLE
replace Sim SD with Sim SE (and Z Score) in stats tables

### PR DESCRIPTION
**Pull request by chad-klumb**
stacked on #702

SE based on `coda::effectiveSize`

works for static and dynamic, formation and dissolution/duration, 1 or  > 1 sim

references #677, #694

### CODE REVIEW

**Comment by smjenness** [comment]
@chad-klumb See related comment on merge conflicts on #723. It looks like some conflicts are similar and some are different.

**Comment by chad-klumb** [comment]
some details of this PR are still being discussed in #677 so I wouldn't merge this until after the 2.3.0 push

**Comment by smjenness** [comment]
@chad-klumb : I am going to merge this PR as I haven't received any other feedback last week. But could you please address the lintr notes here first: https://github.com/EpiModel/EpiModel/runs/7696402805?check_suite_focus=true#step:5:15. You can reproduce these on this branch with `lintr::lint_package()`. Thanks!

**Comment by chad-klumb** [comment]
should be good now

**Review by smjenness — APPROVED** [review]

**Pull request merged**
