### PR TITLE
plotting updates

### PR DESCRIPTION
**Pull request by chad-klumb**
stacked on #693

addresses refactoring, errors, and expanding functionality for `netdx` and `netsim` plotting code

references #698, #695, #676, #662, #457

this is ready for testing, @smjenness @sgoodreau would you mind running through various `plot` calls for `netdx` and `netsim` objects and checking that things look acceptable to you?

### CODE REVIEW

**Comment by sgoodreau** [comment]
@chad-klumb I'm guessing I need the github master versions of some statnet packages? If so, which?  I've been leary about grabbing them until the latest issues with `network` were resolved. But perhaps `tergm` is enough?

Note: my first effort to test this branch (using the CRAN versions of other packages already installed on my computer) led to a novel error, on a very simple model: `Error: ERGM term ‘EdgeAges’ function ‘InitErgmTerm.EdgeAges’ not found`. I'm guessing this is expected.

**Comment by sgoodreau** [comment]
> @chad-klumb I'm guessing I need the github master versions of some statnet packages? If so, which? I've been leary about grabbing them until the latest issues with `network` were resolved. But perhaps `tergm` is enough?
> 
> Note: my first effort to test this branch (using the CRAN versions of other packages already installed on my computer) led to a novel error, on a very simple model: `Error: ERGM term ‘EdgeAges’ function ‘InitErgmTerm.EdgeAges’ not found`. I'm guessing this is expected.

Nevermind, I installed `tergm` from master and it's working now.

**Comment by sgoodreau** [comment]
OK, I've checked against my fairly elaborate `plot.netdx` checking code, and all seems to be good.  I don't have any similarly robust code that covers `plot.netsim`, so I'll let @smjenness dive into that. (But I could write up some basic checks quickly if you want me to).

**Comment by chad-klumb** [comment]
You'll need `tergm@master`; nominally this branch depends on `network@master` but that shouldn't be an issue for these plotting considerations.

**Comment by chad-klumb** [comment]
I ran through a number of plot and print calls for both netsim and netdx and things look reasonable to me.

**Comment by chad-klumb** [comment]
closes #457, #676

**Comment by smjenness** [comment]
I have reviewed and tested against a variety of netsim outputs. All looks good to me, merging.

**Review by smjenness — APPROVED** [review]

**Pull request merged**
