### PR TITLE
add support for ergm.ego

### LINKED ISSUE #653: ergm.ego, netest, simulation, etc.
Interest has been expressed in using `ergm.ego` in `EpiModel`.

It would be ideal to do this in a way that does not introduce additional cases throughout the code.

The separate case handling can probably be contained to `netest` by structuring the output appropriately and switching from `simulate.ergm` calls to `simulate_formula` calls in e.g. `netdx`.  It may be convenient to set `popsize = 0` in the `ergm.ego` call to avoid modification of the model formula.

References #652 (simulation refactoring).

### PR DESCRIPTION
**Pull request by chad-klumb**
stacked on #672

closes #653

### CODE REVIEW

**Comment by smjenness** [comment]
@krivit : please see above. What are your plans to release the current Github master to CRAN?

**Comment by smjenness** [comment]
@martinamorris and @sgoodreau will be beta testing this before merge

**Comment by smjenness** [comment]
@chad-klumb : does this PR require the github devs of any of the statnet packages, including ergm.ego? Or can we remove that? I just was able to update to use the just-CRAN-published tergm.

**Comment by chad-klumb** [comment]
should work with CRAN

**Comment by smjenness** [comment]
@martinamorris : just a reminder to please test this functionality, when you get a chance. Thanks! 🥇

**Pull request merged**
