### PR TITLE
updates to duration 1 handling

### PR DESCRIPTION
**Pull request by chad-klumb**
references #549

stacked on #645 as that introduces nonseparable interfaces which are required for the approach implemented here

the duration 1 case is handled by tergm simulation, producing a networkDynamic as in the duration > 1 case

nw_list has been removed

### CODE REVIEW

**Comment by chad-klumb** [comment]
As noted in #549, there is a choice to be made as to whether we simulate the `duration = 1` case using `ergm` simulation functions and controls or `tergm` simulation functions and controls.  Either approach is possible and can be used to produce valid results.  For consistency of interface we should presumably use the same approach for both "full tergm" and "tergmLite" simulation within `EpiModel` (understanding that `networkDynamics` will be produced only in the "full tergm" case; "tergmLite" simulation will continue to operate based on `edgelists`/`networkLites`, as it does now).

Using `tergm` simulation functions and controls will result in somewhat cleaner `EpiModel` code because all the `networkDynamic` business is handled for us by the `tergm` package.

Using `ergm` simulation functions and controls would require us to handle conversions between `networks` and `networkDynamics` in `EpiModel`, possibly using some "internal" `tergm` functions (that are not currently exported, but could be) for updating the `networkDynamic` after the `ergm` simulation.  This will make `EpiModel` code in the "full tergm" case a bit longer/messier.

Upsides of using `ergm` simulation could include faster simulation times (probably most pertinent to the "tergmLite" case), and controlling the cross-sectional simulation using cross-sectional (i.e., `ergm`) controls.  (It's not clear that the runtime gain would be significant, but `ergm` simulation is probably at least a bit faster than `tergm` simulation for the same cross-sectional model.)  OTOH since `netsim` defines time steps, the simulation is arguably temporal even if the model is cross-sectional, and in that sense `tergm` controls are almost more appropriate.  But this is clearly a matter of opinion.

@smjenness Do you have a preference here?

**Comment by smjenness** [comment]
@chad-klumb : thanks for your work on this. One of the considerations of ergm versus tergm for duration = 1 is whether the tergm approach can actually represent single time step edges. We explored that in #525 with changes implemented in #528. I found earlier that tergms did not allow for consecutive new edges between the same pairs. For example, if an edge existed between two nodes at time step 5, tergms represent that as spanning from steps 5 to 6, and therefore there could not be a new edge between the same two nodes until step 7. Although rare in many full-scale research models, it arose in one users case (the issue filer of #525) and I believe it conceptually makes more sense to have duration=1 models allow for consecutive repeat edges. That was the impetus for the changes in #528, and after I implemented that a bit of the core infrastructure around dynamic networks broke. I hope that addressed your questions, but let me know if not. Thanks!

**Comment by chad-klumb** [comment]
`tergm` simulation can be used to generate the same dynamics as `ergm` simulation by simply using the `ergm` formula and coefficients with `dynamic = TRUE` in the `simulate` call

this differs from the EDA in that `Form` and `Diss` are not used

the EDA dynamics with duration 1 will lead to the non-consecutive behavior you described above

the ergm dynamics will not have this property; a dyad being an edge on consecutive time steps is perfectly allowed

you can see the difference in function calls as follows:

EDA dynamics (`Form` and `Diss` are used):

https://github.com/EpiModel/EpiModel/blob/3f5da0daec027aa92d161145313df655b75fbbe3/R/net.mod.simnet.R#L187-L196

`ergm` dynamics (despite using `tergm` functionality since `dynamic = TRUE`):

https://github.com/EpiModel/EpiModel/blob/3f5da0daec027aa92d161145313df655b75fbbe3/R/net.mod.simnet.R#L200-L209

**Comment by chad-klumb** [comment]
You can see how edge activity is encoded in this scheme in the following example:

```
require(tergm)
set.seed(0)
nw <- network.initialize(10, dir = FALSE)
nwd <- simulate(nw ~ edges, coef = c(0), time.slices = 5, dynamic = TRUE)
nwd$mel[[8]]
```

which produces

```
> nwd$mel[[8]]
$inl
[1] 6

$outl
[1] 5

$atl
$atl$na
[1] FALSE

$atl$active
     [,1] [,2]
[1,]    1    3
[2,]    4    5
```

This means the dyad `5-6` was an edge at times 1, 2, and 4, but not at 3 or 5.

*Given* that the edge was toggled off at time 3, it cannot be toggled back on until time 4, but this does not preclude being an edge at consecutive time steps, as seen at times 1 and 2.

**Comment by smjenness** [comment]
@chad-klumb : excellent example, thanks! It looks like the tergm approach for duration = 1 models is the way to go; I am not too concerned with the runtime issues you noted above as those will be minor. Any other questions before you implement this? Thanks!

**Comment by chad-klumb** [comment]
No other questions come to mind at the moment, just note that tergmLite/EpiModelHIV applications using a cross-sectional model will have their control arguments changed from ergm controls to tergm controls.

I should have these changes done before our next meeting.

**Comment by smjenness** [comment]
@AdrienLeGuillou Please note the change to default controls needed for EpiModelHIV/EpiModelCOVID

**Comment by chad-klumb** [comment]
should be okay to merge now

in `netsim`, the `set.control.ergm` argument is now only used during initialization, and the documentation has been updated accordingly

I've also opened an EpiModelHIV PR with analogous changes

**Review by smjenness — APPROVED** [review]

**Pull request merged**
